@HuanBank_HostAddress = http://localhost:5128

POST {{HuanBank_HostAddress}}/Login
Content-Type: application/json

{
  "Stk": "doquanghuan1",
  "Mk": "2"
}

### 
GET  {{HuanBank_HostAddress}}/GetBalance?stk=doquanghuan
